name: QQQ Drawdown Daily Alert

on:
  schedule:
    # 월~금, 미국 동부시간 기준 오후 5:05 (표준/서머타임 구분 위해 두 번 설정)
    - cron: "5 21 * * 1-5"  # 5:05pm ET during DST (UTC-4)
    - cron: "5 22 * * 1-5"  # 5:05pm ET during Standard Time (UTC-5)
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  run-alert:
    runs-on: ubuntu-latest

    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance

      - name: Run QQQ alert
        run: python qqq_alert.py
